export const mobileMenu = [
    {
        title:"Artworks",
        link:"/artworks"
    },
    {
        title:"Artists",
        link:"/artists"
    },
    {
        title:"sculpture",
        link:"/artworks?cat=sculpture"
    },
    {
        title:"Painting",
        link:"/artworks?cat=paints"
    },
    {
        title:"Photographies",
        link:"/artworks?cat=protographies"
    }
]

export const DesktopMenu = [
    {
        title:"Artworks",
        link:"/artworks"
    },
    {
        title:"Artists",
        link:"/artists"
    },
    {
        title:"sculpture",
        link:"/artworks?cat=sculpture"
    },
    {
        title:"Painting",
        link:"/artworks?cat=paints"
    },
    {
        title:"Photographies",
        link:"/artworks?cat=protographies"
    }
]