export const mobileMenu = [
    {
        title:"Artworks",
        link:"/artworks"
    },
    {
        title:"Artists",
        link:"/artists"
    },
    {
        title:"sculpture",
        link:"/sculpture"
    },
    {
        title:"Painting",
        link:"/paints"
    },
    {
        title:"Photographies",
        link:"/protographies"
    }
]

export const DesktopMenu = [
    {
        title:"Artworks",
        link:"/artworks"
    },
    {
        title:"Artists",
        link:"/artists"
    },
    {
        title:"sculpture",
        link:"/sculpture"
    },
    {
        title:"Painting",
        link:"/paints"
    },
    {
        title:"Photographies",
        link:"/protographies"
    }
]